"""change db

Revision ID: 14395d572785
Revises: 192b0298559f
Create Date: 2024-08-11 08:55:55.027966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14395d572785'
down_revision: Union[str, None] = '192b0298559f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('rating_id', sa.Integer(), nullable=False))
    op.drop_constraint('property_position_id_fkey', 'property', type_='foreignkey')
    op.create_foreign_key(None, 'property', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    op.drop_column('property', 'position_id')
    op.add_column('record', sa.Column('position_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'record', 'position', ['position_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'position_id')
    op.add_column('property', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key('property_position_id_fkey', 'property', 'position', ['position_id'], ['id'], ondelete='CASCADE')
    op.drop_column('property', 'rating_id')
    # ### end Alembic commands ###
