"""add position model

Revision ID: 192b0298559f
Revises: 3119f067d981
Create Date: 2024-08-10 17:24:48.594140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192b0298559f'
down_revision: Union[str, None] = '3119f067d981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('property', sa.Column('position_id', sa.Integer(), nullable=False))
    op.drop_constraint('property_rating_id_fkey', 'property', type_='foreignkey')
    op.create_foreign_key(None, 'property', 'position', ['position_id'], ['id'], ondelete='CASCADE')
    op.drop_column('property', 'rating_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key('property_rating_id_fkey', 'property', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    op.drop_column('property', 'position_id')
    op.drop_table('position')
    # ### end Alembic commands ###
