"""change db

Revision ID: 2ac0454f7801
Revises: 29f4eda8b8ce
Create Date: 2024-08-11 10:27:42.851336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac0454f7801'
down_revision: Union[str, None] = '29f4eda8b8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('position_rating_id_fkey', 'position', type_='foreignkey')
    op.drop_column('position', 'rating_id')
    op.drop_constraint('property_rating_id_fkey', 'property', type_='foreignkey')
    op.drop_column('property', 'rating_id')
    op.add_column('record', sa.Column('rating_id', sa.Integer(), nullable=False))
    op.alter_column('record', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'record', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.alter_column('record', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('record', 'rating_id')
    op.add_column('property', sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('property_rating_id_fkey', 'property', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    op.add_column('position', sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('position_rating_id_fkey', 'position', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
