"""change db

Revision ID: 5bd94873eb0d
Revises: 2ac0454f7801
Create Date: 2024-08-11 10:41:46.215364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd94873eb0d'
down_revision: Union[str, None] = '2ac0454f7801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('rating_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'position', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    op.add_column('property', sa.Column('rating_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'property', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('record_rating_id_fkey', 'record', type_='foreignkey')
    op.drop_column('record', 'rating_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('record_rating_id_fkey', 'record', 'rating', ['rating_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'rating_id')
    op.drop_constraint(None, 'position', type_='foreignkey')
    op.drop_column('position', 'rating_id')
    # ### end Alembic commands ###
